import React from 'react'

const GuestTourism = () => {
    return (
        <div className='max-w-[1560px] w-[100%] min-h-[2100px] h-[100%] bg-[#FCE3E5] flex justify-center items-center'>
            <div className='max-w-[1340px] w-[100%] min-h-[2000px] h-[100%] flex flex-col gap-2 px-[50px] md:px-[100px] py-[40px]'>
                <h1 className='text-[46px] font-Emilio text-[#650010] font-bold'>Tourism</h1>
                <div className='flex-1'>
                    <h1 className='text-[30px] font-Montserrat font-semibold pb-3 text-center text-[#650010]'>Sri Durga Malleswara Swamy varla Devasthanam</h1>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Kanakadurgamma Temple situated on the banks of river Krishna, Indrakeeladri, Vijayawada. This holy shrine of Goddess Durga is a Swayambhu (self-manifested) and is the second largest temple in Andhra Pradesh. On this mountain, goddess Durga had been glowing with the lighting of cores of sun, with golden colour. It’s 18 Km from VIT-AP Campus. </p>
                </div>
                <div className='flex-1 flex flex-col gap-4'>
                    <h1 className='text-[30px] font-Montserrat font-semibold pb-3 text-center text-[#650010]'>Ponnur Anjaneya Swamy Temple</h1>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Ponnur Anjaneya swamy Temple is 28 km from Guntur. Hanuman Jayanthi will be celebrated in a grand for 4 days. Thousands of devotees from nearby places throng the temple during festival days.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Amaravati Amareswara Swamy Temple or Amararama Temple dedicated to Lord Shiva is situated in the Amaravati town, Guntur, Andhra Pradesh. This famous temple is located on the southern bank of the Krishna River is considered to be very sacred and one of the Pancharama Kshetras (five temples) dedicated to Lord Shiva in Andhra Pradesh. It’s 29 Km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Lakshmi Narasimha Temple is a Vaishnavite temple and one of the eight sacred places of Lord Vishnu in India. It is also known for being one of the eight mahakshetras Narasimha in India. It is situated at the foot of the Auspicious Hill in Mangalagiri which is part of the Mangalagiri Tadepalle Municipal Corporation part of Guntur district of Andhra Pradesh, India. It is one of the temples in the series of three temples located on and at the bottom of the hill, the other two being Panakala Narasimha Temple on the hill and Gandala Narasimha Temple at the top of the hill. It has one of the highest gopurams in South India and only one of its type in this part of India. It is 153 feet (47 m) in height and 49 feet (15 m) wide and has eleven storeys. It’s 17 Km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ The Amaravati Archaeological Museum is a museum located in Amaravati, a village in Guntur district of the Indian state of Andhra Pradesh. It is running by Andhra Pradesh tourism. It opens at morning 10:00 am and closed at 5:00 pm and Friday holiday. It also consists modal of Amaravati Mahachaitya. It’s 29 Km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ The Undavalli Caves, a monolithic example of Indian rock-cut architecture and one of the finest testimonials to ancient viswakarma sthapathis, are located in Mangalagiri Tadepalle Municipal Corporation of Guntur district in the Indian state of Andhra Pradesh. The caves are located 6 km south west from Vijayawada, 22 km north east of Guntur City of Andhra Pradesh. It is one of the centrally protected monuments of national importance. It’s 29 Km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Kondapalli Fort, also locally known as Kondapalli Kota, lies to the west of Kondapalli in Vijayawada the second largest city of Andhra Pradesh, India of NTR district, . This historical fort also known as Kondapalli Quilla was built by Prolaya Vema Reddy of Reddi Kingdom during the 14th century CE. It was initially built as a leisure place and business center and later served as a military training base for the British rulers. According to some other historians it was built in 1360 CE by Anna Vema Reddy after he captured Kondapalli from Mudigonda Chalukyas, the fort has been home to several dynasties, from the Reddi rulers to the Nizam Nawabs, and then the East India Company. It’s 40 Km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>
                        ✧ Pavitra Sangamam is located near Ibrahimpatnam by the side of river Krishna. After making a arrangement a stream of water of Godavari river flows through kennels and joins Krishna river at this place. The area is nicely developed with parks and gardens to attract tourist. Boating and water sports facilities are also developed by the side of the Krishna river. Colorful lighting arrangements with high mast towers are constructed to illuminate the area during evening hours.
                        There is an arrangement to perform evening Aarti of Krishna river in line with Ganga Aarti done at Haridwar and Banaras. It’s 33 Km from VIT-AP Campus.
                    </p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ The Uppalapadu Bird Sanctuary is located in Uppalapadu, near Guntur City, India. Painted storks, spot-billed pelicans and other birds that migrate from various countries such as Siberia and Australia use the village water tanks for nesting.The bird population in these tanks used to be around 12,000 previously, however lately only about 7000 birds roost in this dwindling habitat through the year. But some initiatives have taken place such as adding artificial trees, local awareness, proper water supply to the ponds etc. The number of Pelicans, may be more than 1500. Besides this 6 pintail ducks a few cormorant 5 red crested pochard (rhodonesa rufina), common coot, common teal, black-headed ibises, 2 stilts were also sighted. It’s 28 Km’s from VIT-AP Campus.</p>
                </div>
                <div className='flex-1 flex flex-col gap-4'>
                    <h1 className='text-[30px] font-Montserrat font-semibold pb-3 text-center text-[#650010]'>Ponnur Anjaneya Swamy Temple History</h1>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ This temple was built by Kota Jaganatha Swamy in 1969 AD and installed Anjaneya Swamy and Garuda Statues. Anjaneya Swamy is of 24 ft. tall, 12 ft. wide and 4 ft. thickness. This statue carved out of a single black granite rock which was brought under the surveillance of Bhavanarayana Swamy from Edlapadu near Chilakaluripet. There is a temple for Garuda within the temple complex which is of 30 ft. tall, 15 ft. wide and 6 ft. thickness. It’s 60 Km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Kotappakonda is a holy hill, situated in Guntur district, Andhra Pradesh, India. It is located 10 miles from Narasaraopet city and 30 miles south west of Guntur City It’s 95 Km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Celebrated with great devotion and fervor every year with a large number of devotees thronging the place, Kotappakonda has an interesting history and some incredible facts associated with it.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Trikuta Hills: Kotappa Konda hill appears with 3 peaks in any direction so it’s also called as Trikutadri, Trikuta Parvatham. The three hills are Brahma hill, Vishnu hill and Rudra hill. These 3 hills can be distinctly seen from a distance from any direction.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>★ Brahma Shikharam: The main temple Trikoteswara Swamy Temple is located here.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>★ Rudra Shikharam: Old Kotayya temple is located here. This is the first place where Trikoteswara Swamy existed, seeing the great devotion of Devotee Gollabhama, Trikoteswara Swamy came to Brahma Shikharam. Hence it is called Paatha (old) Kotayya Temple.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>★ Vishnu Shikharam: Lord Paapanaseswara Temple is here. It is believed that Lord Vishnu did penance for Lord Shiva. There is also a holy pond “Paapanasa Teertha” here.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Suryalanka Beach or Bapatla Beach is a beach in Guntur District of the Indian state of Andhra Pradesh. It is located approximately 9 kilometers from Bapatla Bhavanarayana Swamy Temple and 50 miles south of Guntur City. It is located in the Bay of Bengal. The place has many resorts close to the beach. It’s 90 km from VIT-AP Campus.</p>
                    <p className='text-[18px] font-Montserrat text-[#000]'>✧ Manginapudi Beach is located on the coast of Bay of Bengal, at a distance of 11 km (6.8 mi) from Machilipatnam of Andhra Pradesh. The beach is maintained by the state tourism board, APTDC.It’s 95 Km from VIT-AP Campus.</p>
                </div>
            </div>
        </div>
    )
}

export default GuestTourism
