name: CI
on:
  push:
    branches: [ AWS-Build-Branch ]
  pull_request:
    branches: [ AWS-Build-Branch ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.5.0'
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy Next.js app
        run: npm run dev
