name: Deploy Next.js App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./vitap-webapp-frontend

      - name: Secure Copy (SCP) to AWS EC2
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -o StrictHostKeyChecking=no -r ./vitap-webapp-frontend/out/* ${{ secrets.SSH_USERNAME }}@${{ secrets.EC2_INSTANCE_IP }}:~/app/
        env:
          SSH_PRIVATE_KEY_PATH: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}

      - name: Build the Next.js app
        run: npx serverless
        working-directory: ./vitap-webapp-frontend
