name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies for frontend
      run: npm --prefix vitap-webapp-frontend install

    - name: Generate frontend lock file
      run: npm --prefix vitap-webapp-frontend ci

    - name: Build frontend
      run: npm --prefix vitap-webapp-frontend run build

    - name: Run frontend tests
      run: npm --prefix vitap-webapp-frontend run test

    - name: Install dependencies for backend
      run: npm --prefix vitap-webapp-backend-strapi install

    - name: Generate backend lock file
      run: npm --prefix vitap-webapp-backend-strapi ci

    - name: Build backend
      run: npm --prefix vitap-webapp-backend-strapi run build

    - name: Run backend tests
      run: npm --prefix vitap-webapp-backend-strapi run test
